### ISSUE TITLE
Crash(Disconnect) of unknown cause

### ISSUE THREAD

**Issue by DeadSix27** [TheCBProject/ForgeMultipart#10]
Not really sure what exactly caused this disconnect, to me the issue it comes random, might be someone else doing something on my server.. however I am the only person crashing.

Stacktrace: https://paste.ubuntu.com/24124545/

**Comment by steampunko** [comment]
I may have an idea to why you crash. Try walking on a block composed of multiparts, then try running on it. Tell me the results

**Comment by covers1624** [comment]
I believe I fixed this in dev the other day.

**Comment by steampunko** [comment]
I've never been able to compile mods from source so I wouldn't be able to use that version

**Comment by covers1624** [comment]
This is fixed in dev pending release.
