### ISSUE TITLE
Major Graphical issue

### ISSUE THREAD

**Issue by steampunko** [TheCBProject/ForgeMultipart#11]
I've been messing around, building objects with Multipart, and now I always get this huge graphical bug that will not go away no matter what I do.
![2017-03-11_15 49 44](https://cloud.githubusercontent.com/assets/16859299/24385699/62f46fae-1320-11e7-8feb-53d80a1d9b2b.png)

**Comment by covers1624** [comment]
Please create a new issue over: https://github.com/TheCBProject/Feedback
Also, attempt to recreate the issue with just FMP and ProjectRed.
A world download will also help a lot.
