### ISSUE TITLE
[1.10.2] Crash on moving a tree with forge-based worldedit

### ISSUE THREAD

**Issue by WildKarrade** [TheCBProject/ForgeMultipart#13]
Everytime someone tries to copy and paste a tree with worldedit on the server I have up for myself and a couple of friends it crashes with that error and that's all the information it gives me.

https://pastebin.com/m54MimkF

**Comment by covers1624** [comment]
Please provide the full crash report.

**Comment by WildKarrade** [comment]
I can give you the full log file but that's the only part outside of chunk location information that is the crash report.

As requested though, that's the full crash text file.
https://pastebin.com/4gFwS3TR

**Comment by covers1624** [comment]
This was fixed in 1.11, unable to easily pull the fix back, and 1.10 is now unsupported.
