### ISSUE TITLE
Server Crash-report

### ISSUE THREAD

**Issue by nicuch** [TheCBProject/ForgeMultipart#14]
`Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 3.5.0-23-generic
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 639389376 bytes (609 MB) / 981467136 bytes (936 MB) up to 981467136 bytes (936 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
	UCH	forge{13.20.0.2228} [Minecraft Forge] (minecraft_server.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCH	jei{4.5.0.289} [Just Enough Items] (jei_1.11.2-4.5.0.289.jar) 
	UCH	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCH	codechickenlib{2.7.0.268} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCH	chickenchunks{2.3.1.65} [ChickenChunks] (ChickenChunks-1.11.2-2.3.1.65-universal.jar) 
	UCH	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.1.114-universal.jar) 
	UCE	forgemultipartcbe{2.1.0.34} [Forge Multipart CBE] (ForgeMultipart-1.11.2-2.1.0.34-universal.jar) 
	UCE	microblockcbe{2.1.0.34} [Forge Microblocks] (ForgeMultipart-1.11.2-2.1.0.34-universal.jar) 
	UCH	minecraftmultipartcbe{2.1.0.34} [Minecraft Multipart Plugin] (ForgeMultipart-1.11.2-2.1.0.34-universal.jar) 
	UCH	hopperducts{1.4.9.1} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.1.jar) 
	UCH	waila{1.8.17} [Waila] (Hwyla-1.8.17-B31_1.11.jar) 
	UCH	ic2{2.7.59-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.59-ex111.jar) 
	UCH	inventorypets{1.4.9.5} [Inventory Pets] (inventorypets-1.11.2-1.4.9.5.jar) 
	UCH	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCH	ironchest{1.11.2-7.0.23.808} [Iron Chest] (ironchest-1.11.2-7.0.23.808.jar) 
	UCH	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCH	mysticalagriculture{1.5.6} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.6.jar) 
	UCH	mysticalagradditions{1.0.2} [Mystical Agradditions] (mysticalagradditions[1.11.2]-1.0.2.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCH	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.3.0.223-universal.jar) 
	UCH	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCH	vrgenerator{5.0.1} [VisibleRayGenerator] (VisibleRayGenerator-1.11.2-5.0.1-universal.jar) 
	UCH	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	UCH	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	UCE	wrcbe{2.1.0} [WirelessRedstone-CBE] (WR-CBE-1.11.2-2.1.0.22-universal.jar) 
	UCH	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.7.59-ex111.jar)
  
NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.223-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
	codechickenlib Invalid Fingerprint Reports: - 1 Invalid Fingerprints!: 
		wrcbe has an invalid fingerprint.
	chickenchunks Invalid Fingerprint Reports: - 1 Invalid Fingerprints!: 
		wrcbe has an invalid fingerprint.
	enderstorage Invalid Fingerprint Reports: - 1 Invalid Fingerprints!: 
		wrcbe has an invalid fingerprint.
	nei Invalid Fingerprint Reports: - 1 Invalid Fingerprints!: 
		wrcbe has an invalid fingerprint.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by covers1624** [comment]
That is not the crash report, that is the crash report details. Also, 1.11 is not supported nor released.

**Comment by nicuch** [comment]
Too fast =) i just updated to pastebin.

**Comment by covers1624** [comment]
Heh, As i though, that is a change i have sitting there in dev for FMP, Parts are being rewritten and this happens to be one of them that is not compatible with the newest CCL.

**Comment by nicuch** [comment]
Sad, on client is working..
