### ISSUE TITLE
MCMultipart Support

### ISSUE THREAD

**Issue by pupnewfster** [TheCBProject/ForgeMultipart#15]
I believe that the microblockcbe mod is part of this mod. Assuming this is accurate if possible it would b nice if the covers and blocks from it could somehow also support MCMultipart. I understand that this is its own library that does something similar (or maybe even the same thing), however most mods I believe only add support for MCMultipart, and it is a shame to not be able to use the covers for any of their cables.

**Comment by covers1624** [comment]
This is on the plate, but its an extremely complex issue to solve, they are both their own multipart api's and its not exactly easy to support one another, Ill close this but i assure you it has no been forgotten.
