### ISSUE TITLE
Not compatilble with thermal expansion 

### ISSUE THREAD

**Issue by DimitriKiew** [TheCBProject/ForgeMultipart#16]
i found that ForgeMultipart is not compatible with the 1.12.2 vesion of ThermalExpantion

**Comment by covers1624** [comment]
Please provide more information, i'm also a developer for CoFH, i doubt there is an actual issue here..

**Comment by DimitriKiew** [comment]
when i try to use the covers with fluix ducts they don't interact as they used to in erlier versons.

**Comment by covers1624** [comment]
Yeah, this isn't an issue, TD doesn't support FMP, or any other multipart api. Please use the covers from TD http://teamcofh.com/docs/covers/
