### ISSUE TITLE
[Suggestion] Option to disable all microblocks

### ISSUE THREAD

**Issue by PanSzelescik** [TheCBProject/ForgeMultipart#17]
This mod is a hard dependency for project red. I don't need microblocks, which take a lot of ram. Option to disable all microblocks would be good

**Comment by covers1624** [comment]
Do you have any statisitcs on the ram usage? They aren't baked models, they use a custom system that's far faster and wayy more efficient on ram. Seems to me you just don't want JEI clogged with microblocks, and that's something i can address.

**Comment by covers1624** [comment]
Also, microblocks, particularly the strips and covers are useful for separating wire connections, they are also used to "cover" a framed wire, similar to what RedPower did, also for colour filtering on pipes using wool strips, and redstone conductivity on pipes using strips of red stone blocks, they are also used in a few recipes, so they actually can't be removed.

**Comment by Frosthaven** [comment]
As a stopgap, jei does allow you to hide items categorically. This is what I do until I actually need them visible.

**Comment by covers1624** [comment]
A JEI plugin has been added. By default all microparts except stone are hidden. There is a config to override this and enable all microparts.

**Comment by ThunderWeed** [comment]
> A JEI plugin has been added. By default all microparts except stone are hidden. There is a config to override this and enable all microparts.

Hello. How do I return all CB Multipart crafting recipes to JEI? Sorry for the stupid question, I don't know much about it :,(
