### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by bgoup** [TheCBProject/ForgeMultipart#18]
Hi! got a server sided crash bug here.
Thanks!

Configuration:
  Minecraft 1.12.2
  Forge 14.23.3.2655/14.23.3.2681 (tested both)
  ChickenASM-1.12-1.0.2.7
  CodeChickenLib-1.12.2-3.1.8.341-universal
  ForgeMultipart-1.12.2-2.4.2.58-universal

![2018-05-14_20 44 07](https://user-images.githubusercontent.com/22617152/40030259-91f9d5d2-57b7-11e8-994e-ba9973bd52a0.png)
Steps to reproduce:
1. Place a redstone torch on top of red block and side of blue block so that they intersect like the two torches pictured.
2. Break the block that you placed the first torch on.

A personal note while testing this:
I have tried this multiple times and sometimes it wont crash in one location if it crashed in the same spot last time. Just change the location and try again.

Client sees something like this: 
![image](https://user-images.githubusercontent.com/22617152/40030571-516a28b2-57b9-11e8-8e6e-5c98d46ae6ce.png)

<details>
  <summary>I get this in my console: (Click to expand)</summary>

>   [21:10:38] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
> java.util.concurrent.ExecutionException: java.util.NoSuchElementException: key not found: minecraft:redstone_torch
> 	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
> Caused by: java.util.NoSuchElementException: key not found: minecraft:redstone_torch
> 	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[MapLike$class.class:?]
> 	at scala.collection.AbstractMap.default(Map.scala:59) ~[AbstractMap.class:?]
> 	at scala.collection.mutable.HashMap.apply(HashMap.scala:65) ~[HashMap.class:?]
> 	at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:155) ~[MultiPartRegistry$.class:?]
> 	at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:216) ~[TileMultipart.class:?]
> 	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:82) ~[MultipartGenerator$.class:?]
> 	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:640) ~[TileMultipart$.class:?]
> 	at codechicken.multipart.TileMultipart.addPart(TileMultipart.scala) ~[TileMultipart.class:?]
> 	at codechicken.multipart.minecraft.EventHandler.place(EventHandler.java:97) ~[EventHandler.class:?]
> 	at codechicken.multipart.minecraft.McMultipartSPH.handlePacket(McMultipartSPH.java:19) ~[McMultipartSPH.class:?]
> 	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:135) ~[PacketCustom$ServerInboundHandler.class:?]
> 	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:133) ~[PacketCustom$ServerInboundHandler.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 5 more
> [21:10:38] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 255
> 	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 255
> 	at codechicken.multipart.MultiPartRegistry$.readPart(MultiPartRegistry.scala:163) ~[MultiPartRegistry$.class:?]
> 	at codechicken.multipart.TileMultipart$.handlePacket(TileMultipart.scala:677) ~[TileMultipart$.class:?]
> 	at codechicken.multipart.handler.MultipartCPH$.handleCompressedTileData(packethandlers.scala:65) ~[MultipartCPH$.class:?]
> 	at codechicken.multipart.handler.MultipartCPH$.handlePacket(packethandlers.scala:36) ~[MultipartCPH$.class:?]
> 	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:110) ~[PacketCustom$ClientInboundHandler.class:?]
> 	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.lambda$handle$0(PacketCustom.java:108) ~[PacketCustom$ClientInboundHandler.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 17 more

</details>
<br>

Your help is appreciated!

**Comment by covers1624** [comment]
Ive got a fix locally, tracking down some other bugs first before a release.

**Comment by JoeSGT** [comment]
Can you post those fixes you have locally because it seem this bug is getting the most attention. Please and thanks you

**Comment by TonyTheGOD** [comment]
@covers1624  my server keep crashing because of this can you release those fixes please?

**Comment by covers1624** [comment]
DumbSlayer, acting like a child is a one way street to getting banned from the server you are on and this tracker. This is a warning, next time you will be blocked from posting issues.  

Now, https://github.com/TheCBProject/ForgeMultipart/commit/b996fe4c0bff80f43c84427490057368799956d2 should fix it, http://chickenbones.net/maven/codechicken/ForgeMultipart/1.12.2-2.4.2.60/ for those who ar impatient, builds are awaiting approval on curse.
