### ISSUE TITLE
Microblocks not reappearing when reloading chunks

### ISSUE THREAD

**Issue by Zarthong** [TheCBProject/ForgeMultipart#19]
When I leave a chunk and come back, my microblocks only sometimes appear, no game crash though.

**Comment by mar-x1** [comment]
Having the exact same issue...chunk loaders seem to help. Not sure what mod is the cause, though.
Any success on a fix?

**Comment by LolHens** [comment]
We are having exactly the same issue on our server but it is even more confusing:
We are playing around with Project Red Frames and when reloading chunks sometimes half of the tunnel bore is missing but when reloading chunks again they suddenly reappear.
It seems like microparts are not loaded sometimes but are not removed from the cunk...

**Comment by lonyelon** [comment]
Same issue as https://github.com/MrTJP/ProjectRed/issues/1277

**Comment by covers1624** [comment]
Cleaning this in to a single issue: TheCBProject/ForgeMultipart#29
