### ISSUE TITLE
Not Compatible with Chisel

### ISSUE THREAD

**Issue by Verticalphase** [TheCBProject/ForgeMultipart#20]
I cannot turn chiseled blocks into Microblocks. 
Minecraft Version: 1.12.2
Mod: Chisel

**Comment by Kalmeira** [comment]
Actually, you cannot turn any non-vanilla blocks into microblocks.

**Comment by Verticalphase** [comment]
Okay are you considering of having it as an option or are you going to add compatibility?

**Comment by Verticalphase** [comment]
Okay, thank you, and thanks for working on an awesome mod!

**Comment by Caaruzo** [comment]
Greeting si have the same issue and was a bit dissapointed hjow it turned. But now when i read it can be enabled for several blocks in configs, there is some hope. I looked into it but couldnt figure out what option and how to use there. maybe someone can tell me please, how to exactly enable a block for chisel?

**Comment by covers1624** [comment]
In 1.14 this will be expanded to just include all non-TileEntities in the cover list. Using the same Slicing pipeline I wrote for AE2's new Facades.
