### ISSUE TITLE
All Capability mutipart tiles returning true for Item Handler capability

### ISSUE THREAD

**Issue by MrTJP** [TheCBProject/ForgeMultipart#21]
Seems like it is hard coded for all capability tiles to return true for Item Handler capability even if none of the parts have this. Some mods rely on this check for connection logic. This makes pipes and such try and connect when they shouldn’t.

**Comment by covers1624** [comment]
Derp, Derp. https://github.com/TheCBProject/ForgeMultipart/commit/3123e8ea6d1285d39a2e3fa42f0a4d9bd3c4c13b
