### ISSUE TITLE
Crash when mixing in JCapabilityProvider in release environment

### ISSUE THREAD

**Issue by MrTJP** [TheCBProject/ForgeMultipart#22]
Seems to be a crash when trying to mix in the JCapabilityProvider trait into TileMultipart. This only happens in release environment. This runs fine in dev. 

Crash Log:
https://pastebin.com/YJWbc9Fy

Classdump for TileMultipart$$8
https://pastebin.com/sbUiL6C0

Classdump for JCapabilityProvider class
https://pastebin.com/xCb4SBAH

**Comment by covers1624** [comment]
Yeah, i have no idea whats going on there.. Ill have to write a testcase, unless PR has something already?

**Comment by covers1624** [comment]
Fixed.
