### ISSUE TITLE
[1.12.2] Error executing task

### ISSUE THREAD

**Issue by Sanofus** [TheCBProject/ForgeMultipart#25]
[crash-2018-06-14_10.51.15-client.txt](https://github.com/TheCBProject/ForgeMultipart/files/2101762/crash-2018-06-14_10.51.15-client.txt)
[crash-2018-06-14_10.51.15-server.txt](https://github.com/TheCBProject/ForgeMultipart/files/2101763/crash-2018-06-14_10.51.15-server.txt)

**Comment by covers1624** [comment]
Duplicate of https://github.com/TheCBProject/ForgeMultipart/issues/18
