### ISSUE TITLE
Microblocks Losing Block Data(?) in Player Inventories on Rejoin

### ISSUE THREAD

**Issue by SilverKytten** [TheCBProject/ForgeMultipart#3]
I've been looking for a similar issue for a few hours, and either can't find any or can't find the right way to describe it.

When a player (regardless of rank or permissions) leaves and rejoins the server, the microblocks in their inventory change to be varied versions of Extra-Utilities' Ender-Thermic Pump. I'm fairly certain this has something to do with us using Thermos (An updated Cauldron/KCauldron, which is Bukkit/Spigot+Forge), as the issue doesn't happen in Single Player. 

Are there any known issues surrounding Thermos and/or any way to fix this?

![2017-01-14_18 03 34](https://cloud.githubusercontent.com/assets/2188185/21959345/b9574846-da89-11e6-93a1-4eebe6bf478a.png)

**Comment by covers1624** [comment]
Sadly i don't know if this is anything FMP end, i would report to thermos and see what they say.

**Comment by SilverKytten** [comment]
OK, thank you.

**Comment by covers1624** [comment]
1.7 is no longer supported sorry.
