### ISSUE TITLE
crash with dimensions [2.4.2.62]

### ISSUE THREAD

**Issue by djesty** [TheCBProject/ForgeMultipart#31]
/!\ Sorry for my english /!\ 
I'm using the 2.4.2.62 version of Multipart CBE and I still have some trouble with dimensions. It's only working in the Overworld. Nether, Twilight Forest, ... still crash.
The first time in any dim, overworld excepted, I have "unknown" displayed with Waila on any block and when I disconnect and reconnect to the map, everything works fine for 2 minutes and then my game freezes with this crash log : 

https://pastebin.com/0446Nws3

**Comment by covers1624** [comment]
Seems to be a weird edge case with things. Fixed in dev.

**Comment by djesty** [comment]
I've tried with the 2.4.2.66 version and it works fine but it's so laggy! my game "can't keep up" and skip so many ticks... I can't even move or do anything, I'm like 1 frame every 10 seconds... (maybe less than that)
