### ISSUE TITLE
CTM render error

### ISSUE THREAD

**Issue by seancrain** [TheCBProject/ForgeMultipart#36]
I did some work to the connected texture system of PureBDcraft in a patch for people who wanted connected textures in a public modpack, which for all practical purposes has to use the [CTM mod](https://minecraft.curseforge.com/projects/ctm) since sp614x rarely gives out permissions for public modpacks.

While it worked fine initially, it began to give me issues a little bit later on, mainly this:
![error](https://i.imgur.com/0KuaUQt.png "Loading Error")

The patch in question is this: https://bdcraft.net/community/work-progress-f8/128x-connected-textures-without-optifine-t6566.html

I don't know what caused it to start malfunctioning as there were no changes made to the files in the pack between when it was working and when it stopped.

**Comment by covers1624** [comment]
Hmm, FMP likely can't resolve the texture from the model's quads, it doesn't simulate render layers when polling for textures. Lemme make some adjustments and see if i can default to the particle texture.
The entire render system for microparts is going to be rewritten soonish anyway.

**Comment by covers1624** [comment]
FMP doesn't support things like CTM at this stage. It will in the future. But please test this build https://cdn.discordapp.com/attachments/159971888485892096/472018445886685184/ForgeMultipart-1.12.2-2.4.2.null-universal.jar

**Comment by seancrain** [comment]
I think this may be part of a larger problem: https://github.com/BuildCraft/BuildCraft/issues/4238

**Comment by covers1624** [comment]
Probably, but there's nothing i can do if it is. Micropart rendering is slated to be rewritten so im going to close this for now.
