### ISSUE TITLE
Texture glitch (no crash, just something weird I noticed)

### ISSUE THREAD

**Issue by Knightcoreframe** [TheCBProject/ForgeMultipart#38]
The dark oak planks slab from Multipart (version 2.4.2.60 for 1.12.2) does not match up with the normal slabs. The texture appears to be flipped in the north/south direction. I'm not sure how I'd fix this myself (not really a code person), but this would likely be a quick fix if I understand what's involved with textures.

It's not a big deal at all, but I thought I'd point it out. Thanks for keeping this going from 1.7!

**Comment by covers1624** [comment]
Yeah.. Its really not that simple sadly. Im going to rewrite the Micropart rendering soon, likely before 1.13.

**Comment by Knightcoreframe** [comment]
Thanks for addressing it so quickly. I hope it goes well!

**Comment by Psy-Virus** [comment]
Still a thing in ForgeMultipart-1.12.2-2.6.0.79-universal
![2018-12-24_15 51 57](https://user-images.githubusercontent.com/6222200/50402201-f9434380-0794-11e9-8ec1-c6391a0eeb5a.png)

Why was this closed if it's not fixed?
