### ISSUE TITLE
[2.5.0.68] Tile Entity old maps

### ISSUE THREAD

**Issue by djesty** [TheCBProject/ForgeMultipart#39]
Hello :)
The problem with the dims seems to be solved and everything works correctly (just a small problem, I'm obliged to disconnect and reconnect to my map when I use a portal cause I'm like in gamemode adventure and I can't break any block and Waila doesn't display blocks correctly) but I'm not here for that, the problem is "Tile Entity", when I try to go on a map from an old version of multipart CBE, I get this error : 
https://pastebin.com/qpYtUAd8  (MultiMC)
https://pastebin.com/a6naxc5c    (Minecraft)

**Comment by JillSwift** [comment]
Same here, I think:

https://pastebin.com/zghvSXCh

**Comment by covers1624** [comment]
Please test with http://chickenbones.net/maven/codechicken/ForgeMultipart/1.12.2-2.5.0.69/ForgeMultipart-1.12.2-2.5.0.69-universal.jar and i will roll the update out immediately.

**Comment by covers1624** [comment]
Thanks.
