### ISSUE TITLE
Can't place Forge Multipart blocks

### ISSUE THREAD

**Issue by IlynPayne** [TheCBProject/ForgeMultipart#40]
After updating Forge MultiPart CBE version (2.4.2.58 -> 2.5.0.69) items from Project Red can't be placed. There is no crash, but log's being flooded with errors and stack traces.

This issue could be caused by one of the Project Red mods, but it appeared after updating Forge Multipart CBE.

[log.txt](https://github.com/TheCBProject/ForgeMultipart/files/2240747/log.txt)

**Comment by covers1624** [comment]
Can i please get your full log?

**Comment by IlynPayne** [comment]
Here you go.
[latest.log](https://github.com/TheCBProject/ForgeMultipart/files/2240924/latest.log)

**Comment by covers1624** [comment]
Please test with https://cdn.discordapp.com/attachments/159971888485892096/473457055353536532/ForgeMultipart-1.12.2-2.5.0.null-universal.jar

**Comment by IlynPayne** [comment]
Everything works fine now, but the version you provided is doing something CPU-intensive in the background (nearly 100% CPU usage on all cores).

**Comment by covers1624** [comment]
I doubt its anything i did, its likely something else on your system. The Minecraft server is single threaded, so it it was MC it would be pinning one core instead of all of them. But anyway, the actual issue here seemed to be with something forge adds, BlockSnapshots, basically allows people to capture blocks being placed, FMP didn't play well with them, but it should be fixed now.

**Comment by IlynPayne** [comment]
> I doubt its anything i did, its likely something else on your system.

I just took two screenshots:
* [good](https://user-images.githubusercontent.com/27144202/43402195-77e4f798-9412-11e8-93b1-fd2c6635c59f.png) - using old version of Forge Multipart
* [bad](https://user-images.githubusercontent.com/27144202/43402219-895d1f8c-9412-11e8-9454-9c3ff856e936.png) - using the version provided by you

They were taken in the exactly same spot, one after another. As you can see, in the *bad* screenshot, on the pie chart there is something called `scheduledExecutables` that causes an extreme lag.
