### ISSUE TITLE
GregTech CE issue

### ISSUE THREAD

**Issue by ShaCraft** [TheCBProject/ForgeMultipart#44]
Using any 1.12.2 versoin of Forge with any FMP version results in this crash.

Trying to place a cover on a gtce wire (it crashes as soon as you point a cover at a wire):

Bad invokespecial instruction: current class isn't assignable to reference class.
https://pastebin.com/k12DG5pv

**Comment by ShaCraft** [comment]
With all up to date mods on Forge 2758 
https://pastebin.com/CU97narx

**Comment by EmosewaPixel** [comment]
Btw, I'd like to mention this only happens outside the dev environment (with GTCE).

**Comment by covers1624** [comment]
Im not farmiliar with GTCE, do they use FMP at all? if so it may be related to https://github.com/TheCBProject/ForgeMultipart/issues/22 Ive had no luck tracking it down so far.

**Comment by Archengius** [comment]
Yeah, that crash is exactly the same as #22. It doesn't happen in dev environment too, and i'm using ICapabilityProvider on my parts.

**Comment by covers1624** [comment]
Ok, Ill leave both these open, ill dig into this issue this weekend, might be simple, maybe not, the mixin stuff is really complicated.

**Comment by covers1624** [comment]
Sorry, havent had time to look into this yet, ill try to get to it after work today.

**Comment by Archengius** [comment]
thanks for "fast" fix

**Comment by covers1624** [comment]
Working on a fix for this now, Seems the Mixin compiler implodes with the inheritance that the mixin has. A More generic capability merging implementation is needed. Ill have this done today.

**Comment by Archengius** [comment]
sooooooooooooo?

**Comment by Archengius** [comment]
I hate to bump issues with no reason, but this one hangs just too long

**Comment by covers1624** [comment]
Should be fixed as of https://github.com/TheCBProject/ForgeMultipart/commit/230f0531f0c9b645e637d99b6022970816436c8c I don't personally have any parts that use capabilities atm, but im working on something. Its fairly simple in the end so it should be fine.
