### ISSUE TITLE
GregTech issue #2

### ISSUE THREAD

**Issue by Black0305** [TheCBProject/ForgeMultipart#47]
Placing a cover on a GT cable crashes.
https://pastebin.com/dKYwt5Me

**Comment by covers1624** [comment]
Can you first try an official build of FMP from [here](http://chickenbones.net/maven/codechicken/ForgeMultipart/), secondly can i get some screenshots of a basic setup before placing the hollow cover, im not exactly sure what code in FMP could cause this..

**Comment by Black0305** [comment]
Updated to an official build and did some testing.
Those two setups crashed. So its not a issue with a hollow cover, its when you place a cover on a cable which is connected to a working diesel generator in this case. https://pastebin.com/9W8XWvdL
Could it be an GT issue?
![cover1](https://user-images.githubusercontent.com/42079463/46640177-c3fe6080-cb6a-11e8-951b-3c98a8a17879.JPG)
![cover3](https://user-images.githubusercontent.com/42079463/46640178-c660ba80-cb6a-11e8-9309-6bff8babbf20.JPG)

**Comment by covers1624** [comment]
Soo, i don't actually know how gregtech works.. I've managed to use the fluid pipes, and cannot confirm this in dev yet, if i could get some more details on how eaxactly to setup this testcase that would be great.
