### ISSUE TITLE
Optifine incompatibility.

### ISSUE THREAD

**Issue by Slayer5934** [TheCBProject/ForgeMultipart#49]
When optifine is installed forge microblocks do not render correctly, same issue with secretrooms mod. https://github.com/AbrarSyed/SecretRoomsMod-forge/issues/256 
![capture](https://user-images.githubusercontent.com/20819543/48662869-68bb6a00-ea56-11e8-8994-71b21e8ed810.PNG)

**Comment by covers1624** [comment]
There is nothing i can do here, Optifine changes the rendering pipeline.
