### ISSUE TITLE
java.lang.NullPointerException: Tessellating CCL block in world (Description: Tessellating CCL block in world)

### ISSUE THREAD

**Issue by phlopsi** [TheCBProject/ForgeMultipart#5]
Was playing on a server and my client crashed. Here's the crash report: https://paste.ee/p/i8XBM

**Comment by phlopsi** [comment]
I assume this is the cause: https://i.imgur.com/QPYeFwq.png

**Comment by covers1624** [comment]
Please create a new issue over here, https://github.com/TheCBProject/Feedback/issues/9 The paste has expired.
