### ISSUE TITLE
Issue with Multipart and Tick Scheduler

### ISSUE THREAD

**Issue by Trellinane** [TheCBProject/ForgeMultipart#55]
Seem to be having random crashes involving codechicken.multipart.

MC 1.12.2
Forge 14.23.5.2808
Code Chicken Lib 3.2.2.353
Forge Multipart CBE 2.6.1.81

[crash-2019-03-04_15.28.42-client.txt](https://github.com/TheCBProject/ForgeMultipart/files/2928127/crash-2019-03-04_15.28.42-client.txt)

Edit:  I have further refined the issue to occur primarily while in dimensions other than the overworld (Nether, Deep Dark, etc.).  Still seems to be very random in timing and frequency.  I can however play for long lengths of time if I stay in the overworld.  I am using FTB Utilities chunk claiming and chunk loading if that is relevant at all.

**Comment by FiveEYZ** [comment]
Hey!, so my server just started to having this issue, from when we first noticed this specific crash (9 hours from writing this) server has crashed 101 times from this, and it continues...

Pack: FTB Revelation 3.0.1
forge-1.12.2-14.23.5.2836-universal
CodeChickenLib-1.12.2-3.2.2.353-universal
ForgeMultipart-1.12.2-2.6.1.81-universal

crash report:
https://gist.github.com/FiveEYZ/e5bcbfb2b3c0413f07aa612073be24e1

here is the debug, u can see it fail to fire event at line 99890
https://gist.github.com/FiveEYZ/063ac06390274153bc8e429f272e1775
