### ISSUE TITLE
TileMultipart sometimes throws exception when it's getCapability is called

### ISSUE THREAD

**Issue by Archengius** [TheCBProject/ForgeMultipart#56]
https://pastebin.com/wR8J35R3

**Comment by Agrax** [comment]
Pretty urgent, if you ask me. When the thing inducing the crash occurs, there’s nothing much can be done: one has to set up the world from a backup.

I had it occur twice: someone placed a torch on a pipe and then broke it. Every chunk in the rendering distance is dangerous as it induces the crash. It’s even worse when using chunk loaders as if the crash occured in a loaded chunk, you can’t even turn the server back on

**Comment by covers1624** [comment]
Paste has been removed, please use gist.

**Comment by Agrax** [comment]
https://gist.github.com/Agrax/8dd0f69b48a264088c1fceb3016776c3

**Comment by Agrax** [comment]
@covers1624 any luck on fixing the issue? :)

**Comment by josiah-roberts** [comment]
:+1: Our server is experiencing world-corruption due to this issue.

**Comment by pyure** [comment]
@covers1624 this bug is a pretty big deal.  Any chance its on your priority list?

**Comment by bdkuhman** [comment]
Any update on this issue?

**Comment by Agrax** [comment]
I wish
