### ISSUE TITLE
Combination of cover and pump kills pump

### ISSUE THREAD

**Issue by pappjm** [TheCBProject/ForgeMultipart#57]
Discovered in GregBlock 2.2.0

I have discovered that if you place both a GT pump and a cover onto a pipe, and then save, quit, and re-load the world, the pump will be gone.

The pump does not disappear if the pipe does not have a cover on it.

If, in the overlay, the pipe shows up as "Forge Multipart CBE", the pump will disappear when reloaded. If the pipe shows up as just "Gregtech Community Edition" it will not disappear.  This seems to be the key, as adding a cover will convert the pipe from GTCE to FMCBE. Removing the cover will not change it back; you have to break the pipe and re-place it to do that. If you add a pump to an FMCBE pipe, even if there are no other covers, it will disappear upon reload.

**Comment by Agrax** [comment]
You should also post it on GTCE github. I think

**Comment by Agrax** [comment]
Or even better: don’t play GregBlock as it has heavily outdated versions of each and every mod that could cause the issue

**Comment by covers1624** [comment]
Likely outdated mods, Bugs related to this were fixed in the past, if you discover it again, please open a new issue.
