### ISSUE TITLE
Server crash with ExceptionInInitializerError in 2.6.2.83

### ISSUE THREAD

**Issue by syntaxaire** [TheCBProject/ForgeMultipart#68]
This has popped up a couple times on this fresh server, preventing it starting, but it's not entirely consistent. meaning trying to start the server again might produce a different result.
[crash-2019-10-22_18.46.26-server.txt](https://github.com/TheCBProject/ForgeMultipart/files/3759357/crash-2019-10-22_18.46.26-server.txt)

**Comment by covers1624** [comment]
Someone is doing parallel class loading when they shouldn't be.
