### ISSUE TITLE
java.util.NoSuchElementException: head of empty list (Description: Rendering item)

### ISSUE THREAD

**Issue by phlopsi** [TheCBProject/ForgeMultipart#7]
Was playing on the same server as in #5 and my client crashed again. Different exception, so here's the crash report: https://paste.ee/p/S1xno
I'll just link to the same image, too: https://i.imgur.com/QPYeFwq.png

**Comment by covers1624** [comment]
Paste has expired: https://github.com/TheCBProject/Feedback/issues/9
