### ISSUE TITLE
Multipart-blocks become instantly breakable

### ISSUE THREAD

**Issue by Heimdell** [TheCBProject/ForgeMultipart#71]
When I place a panel/cover/[framed] cable into a frame, it becomes one-click breakable.

It also stops to be a solid block, i.e., the ladder falls off.

Also, frames tend to break _before_ their content.

All of this makes editing structures unpleasant.

**Comment by covers1624** [comment]
Wrong repo. https://github.com/MrTJP/ProjectRed
