### ISSUE TITLE
Shape of the Frame leads to inaccurate block placement

### ISSUE THREAD

**Issue by Heimdell** [TheCBProject/ForgeMultipart#72]
When I place block on the frame, I have to aim into the center cross on the side, because if I miss block will be placed anywhere but where I want.

How about if the player is sneaking, the Frame is threaten as completely solid block?

Also, let's remove the indentation of the X texture, it causes blocks to be placed on the wrong side.

**Comment by covers1624** [comment]
Wrong repo. https://github.com/MrTJP/ProjectRed
