### ISSUE TITLE
Optifine incompatibility

### ISSUE THREAD

**Issue by SShinkun** [TheCBProject/ForgeMultipart#77]
when loading any version of optifine 1.12.2 with forge multipart the microblocks render incorrectly.

how they render differs but usually is a seemingly high quality grey texture, when another block is placed near it changes to either white or black, and this continues as more blocks are placed, sometimes a stripe of blue or brown can be seen amid the greyscale.

notable settings: 
connected textures (was off during testing so might not be it)
don't recall the exact name but there's a setting that disables textures to be oriented in different ways (like how stone/cobble rotate textures every other block) I have a hunch this is what's causing it.
I hope for a fix but if not possible it would be great if you could identify what setting causes the issue so I can disable it.

**Comment by covers1624** [comment]
Unfortunately, there is nothing that can be done about this..
